import {
  Partner,
  ProductCategory,
  Product,
  PaymentFeeRule,
  Shift,
  Sale,
  MonthlyFee,
  PartnerSettlement,
  AppNotification,
  AuditLog,
} from './types';

export const INITIAL_CATEGORIES: ProductCategory[] = [
  { id: 'cat-aromas', name: 'Aromas & Velas', slug: 'aromas-e-velas', iconName: 'Sparkles' },
  { id: 'cat-gourmet', name: 'Temperos & Sabores', slug: 'temperos-e-sabores', iconName: 'Soup' },
  { id: 'cat-bordados', name: 'Bordados & Decor', slug: 'bordados-e-decor', iconName: 'Palette' },
  { id: 'cat-biojoias', name: 'Biojóias & Acessórios', slug: 'biojoias-e-acessorios', iconName: 'Gem' },
  { id: 'cat-costura', name: 'Costura Criativa', slug: 'costura-criativa', iconName: 'Scissors' },
  { id: 'cat-moda', name: 'Moda Autoral & Afro', slug: 'moda-autoral', iconName: 'Shirt' },
  { id: 'cat-botanica', name: 'Kokedamas & Botânica', slug: 'kokedamas-e-botanica', iconName: 'Flower2' },
  { id: 'cat-infantil', name: 'Infantil Artesanal', slug: 'infantil-artesanal', iconName: 'Baby' },
  { id: 'cat-resina', name: 'Arte em Resina', slug: 'arte-em-resina', iconName: 'Droplets' },
];

export const INITIAL_PARTNERS: Partner[] = [
  {
    id: 'partner-ditodacor',
    name: 'Di Toda Cor',
    tradeName: 'Di Toda Cor Arte & Azulejaria',
    ownerName: 'Keka (Fundadora do Pinta e Borda)',
    document: '05.678.910/0001-34',
    email: 'keka@ditodacor.com.br',
    phone: '(98) 98828-9123',
    whatsapp: '5598988289123',
    instagram: '@ditodacor',
    brandName: 'Di Toda Cor',
    brandDescription: 'Feito à mão e com o coração em São Luís do Maranhão. Azulejos pintados, casinhas coloniais, pratos artísticos e ecobags que celebram a cultura maranhense.',
    brandLogo: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=150&auto=format&fit=crop&q=80',
    category: 'Bordados & Decor',
    pixKey: '98988289123',
    pixKeyType: 'TELEFONE',
    pixHolderName: 'Keka - Di Toda Cor',
    contract: {
      id: 'cont-ditodacor',
      startDate: '2026-01-01',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'partner-tutabel',
    name: 'Tutabel Ateliê Infantil',
    tradeName: 'Tutabel Confecções Artesanais Ltda',
    ownerName: 'Danielle Carvalho',
    document: '12.345.678/0001-90',
    email: 'contato@tutabel.com.br',
    phone: '(98) 98123-4567',
    whatsapp: '5598981234567',
    instagram: '@tutabelatelie',
    brandName: 'Tutabel',
    brandDescription: 'Moda infantil artesanal em tecidos 100% algodão, laços bordados à mão e sapatinhos fofos feitos com amor de mãe.',
    brandLogo: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=150&auto=format&fit=crop&q=80',
    category: 'Infantil Artesanal',
    pixKey: 'danielle@tutabel.com.br',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Danielle Carvalho - Tutabel',
    contract: {
      id: 'cont-tutabel',
      startDate: '2026-01-10',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'partner-armonizzare',
    name: 'Armonizzare Aromas & Velas',
    tradeName: 'Armonizzare Home & Velas',
    ownerName: 'Renata Albuquerque',
    document: '23.456.789/0001-12',
    email: 'renata@armonizzare.com.br',
    phone: '(98) 98234-5678',
    whatsapp: '5598982345678',
    instagram: '@armonizzare.aromas',
    brandName: 'Armonizzare',
    brandDescription: 'Velas aromáticas ecológicas em cera de coco, difusores botânicos e home sprays com fragrâncias reconfortantes.',
    brandLogo: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=150&auto=format&fit=crop&q=80',
    category: 'Aromas & Velas',
    pixKey: '23456789000112',
    pixKeyType: 'CNPJ',
    pixHolderName: 'Armonizzare Home Velas',
    contract: {
      id: 'cont-armonizzare',
      startDate: '2026-02-01',
      monthlyFee: 380,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'partner-preta-chic',
    name: 'Preta Chic Acessórios',
    tradeName: 'Preta Chic Moda Afro',
    ownerName: 'Maria Silva dos Santos',
    document: '34.567.890/0001-23',
    email: 'mariapreta@pretachic.com.br',
    phone: '(98) 98345-6789',
    whatsapp: '5598983456789',
    instagram: '@pretachic.moda',
    brandName: 'Preta Chic',
    brandDescription: 'Acessórios ancestrais, turbantes luxuosos em tecidos africanos, maxi brincos e peças de empoderamento estético.',
    brandLogo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    category: 'Moda Autoral & Afro',
    pixKey: '98983456789',
    pixKeyType: 'TELEFONE',
    pixHolderName: 'Maria Silva - Preta Chic',
    contract: {
      id: 'cont-preta-chic',
      startDate: '2026-01-15',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-01-15T14:30:00Z',
  },
  {
    id: 'partner-mishisaike',
    name: 'MishiSaike Arte Botânica',
    tradeName: 'MishiSaike Kokedamas & Plantas',
    ownerName: 'Clarice Mendes',
    document: '45.678.901/0001-34',
    email: 'clarice@mishisaike.com.br',
    phone: '(98) 98456-7890',
    whatsapp: '5598984567890',
    instagram: '@mishisaike.botanica',
    brandName: 'MishiSaike',
    brandDescription: 'A milenar arte japonesa do kokedama viva, arranjos suspensos, terrários e cerâmicas artesanais exclusivas.',
    brandLogo: 'https://images.unsplash.com/photo-1545241047-6083a3684587?w=150&auto=format&fit=crop&q=80',
    category: 'Kokedamas & Botânica',
    pixKey: 'clarice@mishisaike.com.br',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Clarice Mendes Botânica',
    contract: {
      id: 'cont-mishisaike',
      startDate: '2026-02-15',
      monthlyFee: 420,
      salesCommissionRate: 12,
      commissionBase: 'BRUTO',
      shiftRequirement: 'ISENTO_COM_TAXA', // Marca que não faz plantão! Paga diária de plantonista
      shiftFeePerDay: 75,
      pixMode: 'CENTRALIZADO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-15T11:00:00Z',
  },
  {
    id: 'partner-pikena',
    name: 'Pikena Biojóias do Maranhão',
    tradeName: 'Pikena Artesanatos & Jóias Naturais',
    ownerName: 'Lorena Guimarães',
    document: '56.789.012/0001-45',
    email: 'lorena@pikenabiojoias.com',
    phone: '(98) 98567-8901',
    whatsapp: '5598985678901',
    instagram: '@pikenabiojoias',
    brandName: 'Pikena Biojóias',
    brandDescription: 'Biojóias produzidas com sementes amazônicas e maranhenses, fibras de buriti e prata artesanal, valorizando saberes regionais.',
    brandLogo: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=150&auto=format&fit=crop&q=80',
    category: 'Biojóias & Acessórios',
    pixKey: 'lorena@pikenabiojoias.com',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Lorena Guimarães - Pikena',
    contract: {
      id: 'cont-pikena',
      startDate: '2026-01-20',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'partner-bordando',
    name: 'Bordando Momentos',
    tradeName: 'Bordando Momentos Ateliê',
    ownerName: 'Silvana Rocha',
    document: '67.890.123/0001-56',
    email: 'silvana@bordandomomentos.com',
    phone: '(98) 98678-9012',
    whatsapp: '5598986789012',
    instagram: '@bordando.momentos',
    brandName: 'Bordando Momentos',
    brandDescription: 'Bordado livre afetuoso, bastidores personalizados de maternidade, toalhas de linho e lembranças feitas ponto a ponto.',
    brandLogo: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=150&auto=format&fit=crop&q=80',
    category: 'Bordados & Decor',
    pixKey: 'silvana.rocha@gmail.com',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Silvana Rocha Ateliê',
    contract: {
      id: 'cont-bordando',
      startDate: '2026-02-10',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-10T15:00:00Z',
  },
  {
    id: 'partner-arte-tempero',
    name: 'Arte&Tempero Artesanal',
    tradeName: 'Arte e Tempero Gourmet',
    ownerName: 'Chef Tiago Furtado',
    document: '78.901.234/0001-67',
    email: 'tiago@artetempero.com',
    phone: '(98) 98789-0123',
    whatsapp: '5598987890123',
    instagram: '@artetempero.slz',
    brandName: 'Arte&Tempero',
    brandDescription: 'Sais aromatizados com ervas da horta, molhos de pimenta de cheiro maranhense, azeites defumados e granolas artesanais.',
    brandLogo: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=150&auto=format&fit=crop&q=80',
    category: 'Temperos & Sabores',
    pixKey: '78901234000167',
    pixKeyType: 'CNPJ',
    pixHolderName: 'Arte e Tempero Gourmet',
    contract: {
      id: 'cont-arte-tempero',
      startDate: '2026-03-01',
      monthlyFee: 360,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-03-01T12:00:00Z',
  },
  {
    id: 'partner-sereia',
    name: 'Sereia Ateliê Resina',
    tradeName: 'Sereia Ateliê Artesanato',
    ownerName: 'Beatriz Lemos',
    document: '89.012.345/0001-78',
    email: 'beatriz@sereiaatelie.com',
    phone: '(98) 98890-1234',
    whatsapp: '5598988901234',
    instagram: '@sereia.atelie',
    brandName: 'Sereia Ateliê',
    brandDescription: 'Porta-copos, bandejas e peças de decoração em resina epóxi com areia da Ilha de São Luís, conchas e efeitos de ondas do mar.',
    brandLogo: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=150&auto=format&fit=crop&q=80',
    category: 'Arte em Resina',
    pixKey: 'beatriz.lemos@sereiaatelie.com',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Beatriz Lemos - Sereia',
    contract: {
      id: 'cont-sereia',
      startDate: '2026-02-20',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'partner-ateliedasvelas',
    name: 'Ateliê das Velas',
    tradeName: 'Ateliê das Velas Home & Aromas',
    ownerName: 'Cláudia Mendes',
    document: '90.123.456/0001-89',
    email: 'claudia@ateliedasvelas.com.br',
    phone: '(98) 98877-6655',
    whatsapp: '5598988776655',
    instagram: '@ateliedasvelas.slz',
    brandName: 'Ateliê das Velas',
    brandDescription: 'Velas aromáticas em bombonieres de vidro, cera de coco e essências de canela da Índia e baunilha maranhense.',
    brandLogo: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=150&auto=format&fit=crop&q=80',
    category: 'Aromas & Velas',
    pixKey: '90123456000189',
    pixKeyType: 'CNPJ',
    pixHolderName: 'Ateliê das Velas Home',
    contract: {
      id: 'cont-ateliedasvelas',
      startDate: '2026-02-01',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'partner-bijuqueira',
    name: 'Bijuqueira',
    tradeName: 'Bijuqueira Acessórios e Miçangas',
    ownerName: 'Mariana Fontes',
    document: '01.234.567/0001-90',
    email: 'mariana@bijuqueira.com.br',
    phone: '(98) 98909-8963',
    whatsapp: '5598989098963',
    instagram: '@bijuqueiraa',
    brandName: 'Bijuqueira',
    brandDescription: 'Biojoias étnicas e brincos de arara tecidos em miçangas de vidro, inspirados nas cores e tradições do Maranhão.',
    brandLogo: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=150&auto=format&fit=crop&q=80',
    category: 'Biojóias & Acessórios',
    pixKey: '98989098963',
    pixKeyType: 'TELEFONE',
    pixHolderName: 'Mariana Fontes - Bijuqueira',
    contract: {
      id: 'cont-bijuqueira',
      startDate: '2026-01-15',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'partner-coisasdakekel',
    name: 'Coisas da Kekel',
    tradeName: 'Coisas da Kekel Crochê',
    ownerName: 'Raquel "Kekel" Matos',
    document: '12.345.678/0001-01',
    email: 'kekel@coisasdakekel.com',
    phone: '(98) 98833-9771',
    whatsapp: '5598988339771',
    instagram: '@coisasdakekel',
    brandName: 'Coisas da Kekel',
    brandDescription: 'Bolsas estruturadas em fio de malha e algodão com alças em couro legítimo, laços artesanais e acessórios elegantes.',
    brandLogo: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=150&auto=format&fit=crop&q=80',
    category: 'Costura Criativa',
    pixKey: 'kekel@coisasdakekel.com',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Raquel Matos - Kekel',
    contract: {
      id: 'cont-coisasdakekel',
      startDate: '2026-02-15',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-15T14:00:00Z',
  },
  {
    id: 'partner-donasdomundo',
    name: 'Donas do Mundo',
    tradeName: 'Donas do Mundo Velas & Afeto',
    ownerName: 'Amanda Castro',
    document: '23.456.789/0001-12',
    email: 'amanda@donasdomundo.com',
    phone: '(98) 99118-0613',
    whatsapp: '5598991180613',
    instagram: '@donasdomundo02',
    brandName: 'Donas do Mundo',
    brandDescription: 'Linha "Na Lua Cheia": Velas com cera vegetal em potes de vidro com tampa de madeira, cristais energéticos e poemas de acolhimento.',
    brandLogo: 'https://images.unsplash.com/photo-1572726729437-3732646279f6?w=150&auto=format&fit=crop&q=80',
    category: 'Aromas & Velas',
    pixKey: 'amanda@donasdomundo.com',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Amanda Castro - Donas do Mundo',
    contract: {
      id: 'cont-donasdomundo',
      startDate: '2026-01-20',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-01-20T16:00:00Z',
  },
  {
    id: 'partner-madreartemis',
    name: 'Madre Artemis',
    tradeName: 'Madre Artemis Joalheria Mística',
    ownerName: 'Lívia Andrade',
    document: '34.567.890/0001-23',
    email: 'livia@madreartemis.com',
    phone: '(98) 99171-5912',
    whatsapp: '5598991715912',
    instagram: '@madre.artemis',
    brandName: 'Madre Artemis',
    brandDescription: 'Joias e amuletos em macramê com pedras brutas e lapidadas (pedra da lua, amazonita, quartzo solar e ametista).',
    brandLogo: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=150&auto=format&fit=crop&q=80',
    category: 'Biojóias & Acessórios',
    pixKey: '98991715912',
    pixKeyType: 'TELEFONE',
    pixHolderName: 'Lívia Andrade - Madre Artemis',
    contract: {
      id: 'cont-madreartemis',
      startDate: '2026-02-10',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-10T12:00:00Z',
  },
  {
    id: 'partner-vooa',
    name: 'Vooa Design Solar',
    tradeName: 'Vooa Óculos e Acessórios',
    ownerName: 'Tatiana Gusmão',
    document: '45.678.901/0001-34',
    email: 'tatiana@vooa.com.br',
    phone: '(98) 98163-9234',
    whatsapp: '5598981639234',
    instagram: '@use.vooa',
    brandName: 'Vooa',
    brandDescription: 'Óculos de sol solares de design moderno, armações esportivas e urbanas com proteção UV400 para o sol maranhense.',
    brandLogo: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=150&auto=format&fit=crop&q=80',
    category: 'Biojóias & Acessórios',
    pixKey: 'tatiana@vooa.com.br',
    pixKeyType: 'EMAIL',
    pixHolderName: 'Tatiana Gusmão - Vooa',
    contract: {
      id: 'cont-vooa',
      startDate: '2026-02-15',
      monthlyFee: 350,
      salesCommissionRate: 10,
      commissionBase: 'BRUTO',
      shiftRequirement: 'REGULAR',
      shiftFeePerDay: 0,
      pixMode: 'DIRETO',
      status: 'ATIVO',
    },
    createdAt: '2026-02-15T15:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-00',
    sku: 'DTC-001',
    name: 'Azulejo Maranhense Pintado à Mão - Casinhas de São Luís',
    description: 'Peça autoral pintada à mão por Keka (idealizadora do projeto). Azulejo cerâmico esmaltado 15x15cm retratando os casarões coloniais do Centro Histórico.',
    partnerId: 'partner-ditodacor',
    categoryId: 'cat-bordados',
    price: 75.00,
    costPrice: 28.00,
    stock: 10,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'prod-01',
    sku: 'TUT-001',
    name: 'Vestidinho Infantil Floral Algodão',
    description: 'Vestido confeccionado em tricoline 100% algodão premium, com gola boneca em bordado inglês e laço traseiro ajustável. Tamanhos 1 a 4 anos.',
    partnerId: 'partner-tutabel',
    categoryId: 'cat-infantil',
    price: 119.90,
    costPrice: 55.00,
    stock: 7,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-15T11:00:00Z',
  },
  {
    id: 'prod-02',
    sku: 'TUT-002',
    name: 'Kit 3 Laços Bordados no Linho',
    description: 'Trio de laços delicados aplicados na faixinha de meia de seda ou bico de pato com dentinhos forrado. Bordados à mão com mini rococós.',
    partnerId: 'partner-tutabel',
    categoryId: 'cat-infantil',
    price: 49.90,
    costPrice: 18.00,
    stock: 14,
    minStock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&auto=format&fit=crop&q=80',
    isFeatured: false,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-05T09:30:00Z',
    updatedAt: '2026-08-05T09:30:00Z',
  },
  {
    id: 'prod-03',
    sku: 'ARM-001',
    name: 'Vela Aromática Flor de Laranjeira & Cedro',
    description: 'Vela artesanal em pote de vidro âmbar com tampa de madeira nobre. 180g de cera vegetal de coco, pavio 100% algodão e aroma marcante.',
    partnerId: 'partner-armonizzare',
    categoryId: 'cat-aromas',
    price: 68.00,
    costPrice: 28.00,
    stock: 12,
    minStock: 4,
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
  },
  {
    id: 'prod-04',
    sku: 'ARM-002',
    name: 'Difusor de Varetas Alecrim do Campo 250ml',
    description: 'Difusor de ambiente com varetas de fibra de alta absorção que propagam o frescor do alecrim e notas herbais pela casa o dia todo.',
    partnerId: 'partner-armonizzare',
    categoryId: 'cat-aromas',
    price: 79.90,
    costPrice: 32.00,
    stock: 8,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80',
    isFeatured: false,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-12T11:20:00Z',
    updatedAt: '2026-08-12T11:20:00Z',
  },
  {
    id: 'prod-05',
    sku: 'PRE-001',
    name: 'Turbante Aramado Estampa Samakaka',
    description: 'Turbante anatômico com estrutura em arame maleável, fácil de moldar em menos de 10 segundos. Tecido africano autêntico em cores vibrantes.',
    partnerId: 'partner-preta-chic',
    categoryId: 'cat-moda',
    price: 58.00,
    costPrice: 22.00,
    stock: 9,
    minStock: 4,
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-02T13:40:00Z',
    updatedAt: '2026-08-18T10:00:00Z',
  },
  {
    id: 'prod-06',
    sku: 'PRE-002',
    name: 'Maxi Brinco Étnico Dourado & Miçangas',
    description: 'Brinco leve e imponente, base antialérgica com banho flash e tecelagem manual em miçangas pretas e terracota. Design autoral.',
    partnerId: 'partner-preta-chic',
    categoryId: 'cat-moda',
    price: 45.00,
    costPrice: 15.00,
    stock: 15,
    minStock: 4,
    imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80',
    isFeatured: false,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-04T16:15:00Z',
    updatedAt: '2026-08-04T16:15:00Z',
  },
  {
    id: 'prod-07',
    sku: 'MIS-001',
    name: 'Kokedama Ficus Ginseng com Prato de Barro',
    description: 'Árvore em miniatura cultivada em esfera de musgo vivo e substrato especial. Acompanha base de cerâmica artesanal queimada em alta temperatura.',
    partnerId: 'partner-mishisaike',
    categoryId: 'cat-botanica',
    price: 135.00,
    costPrice: 58.00,
    stock: 5,
    minStock: 2,
    imageUrl: 'https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-08T09:00:00Z',
    updatedAt: '2026-08-25T14:30:00Z',
  },
  {
    id: 'prod-08',
    sku: 'MIS-002',
    name: 'Mini Terrário Fechado com Musgos e Fittonias',
    description: 'Ecossistema autosustentável em frasco de vidro de boticário com tampa de cortiça natural. Exige rega apenas a cada 3 a 6 meses.',
    partnerId: 'partner-mishisaike',
    categoryId: 'cat-botanica',
    price: 85.00,
    costPrice: 35.00,
    stock: 6,
    minStock: 2,
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&auto=format&fit=crop&q=80',
    isFeatured: false,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-11T15:00:00Z',
    updatedAt: '2026-08-11T15:00:00Z',
  },
  {
    id: 'prod-09',
    sku: 'PIK-001',
    name: 'Colar Biojóia Sementes de Jarina e Buriti',
    description: 'Colar com marfim vegetal (semente de jarina polida) e trançado em fibra de buriti maranhense. Acabamento ajustável em macramê.',
    partnerId: 'partner-pikena',
    categoryId: 'cat-biojoias',
    price: 72.00,
    costPrice: 26.00,
    stock: 11,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-07T11:00:00Z',
    updatedAt: '2026-08-22T17:10:00Z',
  },
  {
    id: 'prod-10',
    sku: 'BOR-001',
    name: 'Bastidor Decorativo Floral 20cm Linho Misto',
    description: 'Bastidor em bambu com bordado livre em tons terrosos, representando a flora e poesia maranhense. Ideal para compor gallery wall.',
    partnerId: 'partner-bordando',
    categoryId: 'cat-bordados',
    price: 89.00,
    costPrice: 30.00,
    stock: 4,
    minStock: 2,
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-03T10:45:00Z',
    updatedAt: '2026-08-19T13:20:00Z',
  },
  {
    id: 'prod-11',
    sku: 'ART-001',
    name: 'Kit 3 Sais Gourmet Defumados da Ilha',
    description: 'Trilogia de sais marinhos artesanais: Sal com Pimenta de Cheiro e Louro, Sal com Alho Negro e Sal de Ervas Frescas. Frascos de 120g com moedor.',
    partnerId: 'partner-arte-tempero',
    categoryId: 'cat-gourmet',
    price: 65.00,
    costPrice: 24.00,
    stock: 16,
    minStock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-09T16:00:00Z',
    updatedAt: '2026-08-27T10:00:00Z',
  },
  {
    id: 'prod-12',
    sku: 'SER-001',
    name: 'Conjunto 4 Porta-Copos Ondas de São Luís em Resina',
    description: 'Porta-copos hexagonais em resina cristalina translúcida com pigmentos azul turquesa e areia natural das praias de São Luís/MA.',
    partnerId: 'partner-sereia',
    categoryId: 'cat-resina',
    price: 75.00,
    costPrice: 28.00,
    stock: 7,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-14T14:20:00Z',
    updatedAt: '2026-08-26T12:00:00Z',
  },
  {
    id: 'prod-13',
    sku: 'ATV-001',
    name: 'Vela Artesanal Bomboniere Canela & Baunilha Maranhense',
    description: 'Vela aromática em bomboniere de vidro canelado com cera vegetal de coco e pavio de algodão. Aroma quente e acolhedor de 200g.',
    partnerId: 'partner-ateliedasvelas',
    categoryId: 'cat-aromas',
    price: 72.00,
    costPrice: 30.00,
    stock: 9,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-28T14:00:00Z',
  },
  {
    id: 'prod-14',
    sku: 'BIJ-001',
    name: 'Brinco Arara em Miçangas Tecidas à Mão',
    description: 'Biojoia autoral confeccionada ponto a ponto em miçangas de vidro de alta precisão com as cores vivas das araras maranhenses. Super leve.',
    partnerId: 'partner-bijuqueira',
    categoryId: 'cat-biojoias',
    price: 68.00,
    costPrice: 24.00,
    stock: 12,
    minStock: 4,
    imageUrl: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: '2026-08-25T16:00:00Z',
  },
  {
    id: 'prod-15',
    sku: 'COI-001',
    name: 'Bolsa Estruturada em Crochê com Alça de Couro Legítimo',
    description: 'Bolsa de crochê contemporâneo em fio nobre, forrada com tecido tricoline e fecho magnético dourado. Acompanha alça transversal regulável.',
    partnerId: 'partner-coisasdakekel',
    categoryId: 'cat-costura',
    price: 185.00,
    costPrice: 75.00,
    stock: 5,
    minStock: 2,
    imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-18T15:30:00Z',
    updatedAt: '2026-08-29T10:15:00Z',
  },
  {
    id: 'prod-16',
    sku: 'DON-001',
    name: 'Vela Terapêutica "Na Lua Cheia" com Quartzo Rosa',
    description: 'Vela botânica com cera de coco, óleo essencial de lavanda francesa e cristal de quartzo rosa autêntico para rituais de autocuidado.',
    partnerId: 'partner-donasdomundo',
    categoryId: 'cat-aromas',
    price: 78.00,
    costPrice: 32.00,
    stock: 10,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1572726729437-3732646279f6?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-19T09:00:00Z',
    updatedAt: '2026-08-28T11:00:00Z',
  },
  {
    id: 'prod-17',
    sku: 'MAD-001',
    name: 'Colar em Macramê com Pedra da Lua Bruta',
    description: 'Joia artesanal mística tecida à mão em fio encerado impermeável de alta resistência, engastando uma pedra da lua natural autêntica.',
    partnerId: 'partner-madreartemis',
    categoryId: 'cat-biojoias',
    price: 89.00,
    costPrice: 34.00,
    stock: 8,
    minStock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-08-27T17:00:00Z',
  },
  {
    id: 'prod-18',
    sku: 'VOO-001',
    name: 'Óculos Solar Urbano Armação Translúcida Âmbar UV400',
    description: 'Óculos de sol contemporâneos com lentes polarizadas com proteção total UV400. Design solar sofisticado e leve para a luminosidade maranhense.',
    partnerId: 'partner-vooa',
    categoryId: 'cat-biojoias',
    price: 139.00,
    costPrice: 55.00,
    stock: 11,
    minStock: 4,
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
    isFeatured: true,
    isPublished: true,
    isActive: true,
    createdAt: '2026-08-21T16:20:00Z',
    updatedAt: '2026-08-29T12:00:00Z',
  },
];

export const INITIAL_FEE_RULES: PaymentFeeRule[] = [
  {
    id: 'fee-pix-direto',
    terminalName: 'Pix Direto Marca',
    cardBrand: 'TODAS',
    modality: 'PIX',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 0.0,
    active: true,
    notes: 'Pix transferido direto para a chave Pix do artesão proprietário (sem taxa)',
  },
  {
    id: 'fee-pix-centralizado',
    terminalName: 'Pix Centralizado P&B',
    cardBrand: 'TODAS',
    modality: 'PIX',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 0.99,
    active: true,
    notes: 'Taxa operacional da conta Pinta e Borda para conciliação',
  },
  {
    id: 'fee-stone-debito',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'VISA',
    modality: 'DEBITO',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 1.99,
    active: true,
  },
  {
    id: 'fee-stone-debito-master',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'MASTERCARD',
    modality: 'DEBITO',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 1.99,
    active: true,
  },
  {
    id: 'fee-stone-debito-elo',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'ELO',
    modality: 'DEBITO',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 2.39,
    active: true,
  },
  {
    id: 'fee-stone-cred-1x',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'VISA',
    modality: 'CREDITO_VISTA',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 3.99,
    active: true,
  },
  {
    id: 'fee-stone-cred-1x-master',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'MASTERCARD',
    modality: 'CREDITO_VISTA',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 3.99,
    active: true,
  },
  {
    id: 'fee-stone-cred-1x-elo',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'ELO',
    modality: 'CREDITO_VISTA',
    installmentsMin: 1,
    installmentsMax: 1,
    feePercentage: 4.49,
    active: true,
  },
  {
    id: 'fee-stone-cred-2a6',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'TODAS',
    modality: 'CREDITO_PARCELADO',
    installmentsMin: 2,
    installmentsMax: 6,
    feePercentage: 7.89,
    active: true,
  },
  {
    id: 'fee-stone-cred-7a12',
    terminalName: 'Stone Maquininha Balcão',
    cardBrand: 'TODAS',
    modality: 'CREDITO_PARCELADO',
    installmentsMin: 7,
    installmentsMax: 12,
    feePercentage: 11.49,
    active: true,
  },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift-today-01',
    partnerId: 'partner-tutabel',
    partnerName: 'Tutabel',
    operatorUserId: 'user-danielle',
    operatorName: 'Danielle Carvalho (Tutabel)',
    startTime: '2026-09-02T10:00:00Z',
    status: 'ATIVO',
    salesCount: 4,
    totalSalesAmount: 382.80,
    notes: 'Turno da manhã no Rio Anil Shopping. Movimento constante.',
  },
  {
    id: 'shift-yesterday-02',
    partnerId: 'partner-preta-chic',
    partnerName: 'Preta Chic',
    operatorUserId: 'user-maria',
    operatorName: 'Maria Silva (Preta Chic)',
    startTime: '2026-09-01T14:00:00Z',
    endTime: '2026-09-01T22:00:00Z',
    durationMinutes: 480,
    status: 'ENCERRADO',
    salesCount: 9,
    totalSalesAmount: 764.50,
    notes: 'Turno da tarde/noite encerrado com fechamento sem divergências.',
  },
  {
    id: 'shift-yesterday-01',
    partnerId: 'partner-armonizzare',
    partnerName: 'Armonizzare',
    operatorUserId: 'user-renata',
    operatorName: 'Renata Albuquerque (Armonizzare)',
    startTime: '2026-09-01T10:00:00Z',
    endTime: '2026-09-01T14:00:00Z',
    durationMinutes: 240,
    status: 'ENCERRADO',
    salesCount: 5,
    totalSalesAmount: 418.00,
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-001',
    saleNumber: '#PB-2026-0182',
    timestamp: '2026-09-02T10:42:00Z',
    shiftId: 'shift-today-01',
    operatorId: 'partner-tutabel',
    operatorName: 'Danielle Carvalho (Tutabel)',
    customerName: 'Camila Mendonça',
    customerPhone: '(98) 99122-3344',
    paymentMethod: 'CREDITO',
    paymentDetails: {
      terminalName: 'Stone Maquininha Balcão',
      cardBrand: 'VISA',
      installments: 1,
      feePercentageApplied: 3.99,
      feeAmountTotal: 7.50,
    },
    items: [
      {
        id: 'item-001-1',
        productId: 'prod-01',
        productName: 'Vestidinho Infantil Floral Algodão',
        productSku: 'TUT-001',
        partnerId: 'partner-tutabel',
        partnerName: 'Tutabel',
        unitPrice: 119.90,
        quantity: 1,
        subtotal: 119.90,
        feePercentageApplied: 3.99,
        feeAmount: 4.78,
        pintaBordaCommissionRate: 10,
        pintaBordaCommissionAmount: 11.99,
        netAmountToPartner: 103.13,
      },
      {
        id: 'item-001-2',
        productId: 'prod-03',
        productName: 'Vela Aromática Flor de Laranjeira & Cedro',
        productSku: 'ARM-001',
        partnerId: 'partner-armonizzare',
        partnerName: 'Armonizzare',
        unitPrice: 68.00,
        quantity: 1,
        subtotal: 68.00,
        feePercentageApplied: 3.99,
        feeAmount: 2.71,
        pintaBordaCommissionRate: 10,
        pintaBordaCommissionAmount: 6.80,
        netAmountToPartner: 58.49,
      },
    ],
    totalGross: 187.90,
    totalFees: 7.49,
    totalPintaBordaCommission: 18.79,
    totalNetToPartners: 161.62,
    status: 'PAGO',
  },
  {
    id: 'sale-002',
    saleNumber: '#PB-2026-0183',
    timestamp: '2026-09-02T11:15:00Z',
    shiftId: 'shift-today-01',
    operatorId: 'partner-tutabel',
    operatorName: 'Danielle Carvalho (Tutabel)',
    customerName: 'Lucas Ferreira',
    paymentMethod: 'PIX_DIRETO',
    paymentDetails: {
      terminalName: 'Pix Direto Marca',
      installments: 1,
      feePercentageApplied: 0,
      feeAmountTotal: 0,
      pixTxId: 'PIX-ARM-9988223311',
      pixConfirmedAt: '2026-09-02T11:15:20Z',
    },
    items: [
      {
        id: 'item-002-1',
        productId: 'prod-03',
        productName: 'Vela Aromática Flor de Laranjeira & Cedro',
        productSku: 'ARM-001',
        partnerId: 'partner-armonizzare',
        partnerName: 'Armonizzare',
        unitPrice: 68.00,
        quantity: 1,
        subtotal: 68.00,
        feePercentageApplied: 0,
        feeAmount: 0,
        pintaBordaCommissionRate: 10,
        pintaBordaCommissionAmount: 6.80,
        netAmountToPartner: 61.20,
      },
    ],
    totalGross: 68.00,
    totalFees: 0,
    totalPintaBordaCommission: 6.80,
    totalNetToPartners: 61.20,
    status: 'PAGO',
  },
  {
    id: 'sale-003',
    saleNumber: '#PB-2026-0184',
    timestamp: '2026-09-02T12:05:00Z',
    shiftId: 'shift-today-01',
    operatorId: 'partner-tutabel',
    operatorName: 'Danielle Carvalho (Tutabel)',
    customerName: 'Juliana Costa',
    paymentMethod: 'DEBITO',
    paymentDetails: {
      terminalName: 'Stone Maquininha Balcão',
      cardBrand: 'MASTERCARD',
      installments: 1,
      feePercentageApplied: 1.99,
      feeAmountTotal: 2.53,
    },
    items: [
      {
        id: 'item-003-1',
        productId: 'prod-05',
        productName: 'Turbante Aramado Estampa Samakaka',
        productSku: 'PRE-001',
        partnerId: 'partner-preta-chic',
        partnerName: 'Preta Chic',
        unitPrice: 58.00,
        quantity: 1,
        subtotal: 58.00,
        feePercentageApplied: 1.99,
        feeAmount: 1.15,
        pintaBordaCommissionRate: 10,
        pintaBordaCommissionAmount: 5.80,
        netAmountToPartner: 51.05,
      },
      {
        id: 'item-003-2',
        productId: 'prod-09',
        productName: 'Colar Biojóia Sementes de Jarina e Buriti',
        productSku: 'PIK-001',
        partnerId: 'partner-pikena',
        partnerName: 'Pikena Biojóias',
        unitPrice: 72.00,
        quantity: 1,
        subtotal: 72.00,
        feePercentageApplied: 1.99,
        feeAmount: 1.43,
        pintaBordaCommissionRate: 10,
        pintaBordaCommissionAmount: 7.20,
        netAmountToPartner: 63.37,
      },
    ],
    totalGross: 130.00,
    totalFees: 2.58,
    totalPintaBordaCommission: 13.00,
    totalNetToPartners: 114.42,
    status: 'PAGO',
  },
];

export const INITIAL_MONTHLY_FEES: MonthlyFee[] = [
  {
    id: 'fee-tutabel-09',
    partnerId: 'partner-tutabel',
    partnerName: 'Tutabel',
    competency: '09/2026',
    amount: 350.00,
    dueDate: '2026-09-10',
    status: 'ABERTO',
    discount: 0,
  },
  {
    id: 'fee-armonizzare-09',
    partnerId: 'partner-armonizzare',
    partnerName: 'Armonizzare',
    competency: '09/2026',
    amount: 380.00,
    dueDate: '2026-09-10',
    status: 'ABERTO',
    discount: 0,
  },
  {
    id: 'fee-preta-09',
    partnerId: 'partner-preta-chic',
    partnerName: 'Preta Chic',
    competency: '09/2026',
    amount: 350.00,
    dueDate: '2026-09-10',
    status: 'PAGO',
    paidAt: '2026-09-01T16:00:00Z',
    discount: 0,
  },
  {
    id: 'fee-mishi-09',
    partnerId: 'partner-mishisaike',
    partnerName: 'MishiSaike',
    competency: '09/2026',
    amount: 420.00,
    dueDate: '2026-09-10',
    status: 'ABERTO',
    discount: 0,
    notes: 'Possui taxa de diarista por não fazer plantão',
  },
];

export const INITIAL_SETTLEMENTS: PartnerSettlement[] = [
  {
    id: 'settle-arm-ago-2',
    partnerId: 'partner-armonizzare',
    partnerName: 'Armonizzare',
    period: '16/08/2026 a 31/08/2026',
    totalSalesGross: 1420.00,
    totalCardFeesDeducted: 42.60,
    totalCommissionDeducted: 142.00,
    shiftFeeDeducted: 0,
    monthlyFeeDeducted: 0,
    adjustments: 0,
    netPayoutAmount: 1235.40,
    status: 'PAGO',
    paidAt: '2026-09-01T18:00:00Z',
    pixUsed: '23456789000112',
  },
  {
    id: 'settle-tut-ago-2',
    partnerId: 'partner-tutabel',
    partnerName: 'Tutabel',
    period: '16/08/2026 a 31/08/2026',
    totalSalesGross: 1890.00,
    totalCardFeesDeducted: 56.70,
    totalCommissionDeducted: 189.00,
    shiftFeeDeducted: 0,
    monthlyFeeDeducted: 0,
    adjustments: 0,
    netPayoutAmount: 1644.30,
    status: 'PAGO',
    paidAt: '2026-09-01T18:30:00Z',
    pixUsed: 'danielle@tutabel.com.br',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    recipientPartnerId: 'partner-armonizzare',
    type: 'SALE_NOTIFICATION',
    title: 'Venda Realizada no Balcão!',
    message: 'Seu item "Vela Aromática Flor de Laranjeira" foi vendido por Danielle Carvalho (Tutabel). Líquido a receber: R$ 58,49.',
    timestamp: '2026-09-02T10:42:05Z',
    isRead: false,
  },
  {
    id: 'notif-02',
    recipientPartnerId: 'partner-preta-chic',
    type: 'SALE_NOTIFICATION',
    title: 'Venda Realizada no Balcão!',
    message: 'Seu item "Turbante Samakaka" foi vendido por Danielle Carvalho (Tutabel). Líquido a receber: R$ 51,05.',
    timestamp: '2026-09-02T12:05:05Z',
    isRead: false,
  },
  {
    id: 'notif-03',
    recipientPartnerId: 'partner-mishisaike',
    type: 'LOW_STOCK',
    title: 'Alerta de Estoque Mínimo',
    message: 'O produto "Kokedama Ficus Ginseng" atingiu o saldo de 5 unidades na loja física do Rio Anil Shopping.',
    timestamp: '2026-09-02T09:00:00Z',
    isRead: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-01',
    timestamp: '2026-09-02T10:00:00Z',
    userId: 'user-danielle',
    userName: 'Danielle Carvalho',
    role: 'PARTNER',
    action: 'INICIO_EXPEDIENTE',
    entity: 'Shift',
    entityId: 'shift-today-01',
    details: 'Iniciou expediente da manhã na loja física do Rio Anil Shopping.',
  },
  {
    id: 'audit-02',
    timestamp: '2026-09-02T10:42:00Z',
    userId: 'user-danielle',
    userName: 'Danielle Carvalho',
    role: 'PARTNER',
    action: 'CRIAR_VENDA',
    entity: 'Sale',
    entityId: 'sale-001',
    details: 'Venda #PB-2026-0182 de R$ 187,90 registrada com sucesso (Cartão de Crédito 1x Visa).',
  },
  {
    id: 'audit-03',
    timestamp: '2026-09-02T12:05:00Z',
    userId: 'user-danielle',
    userName: 'Danielle Carvalho',
    role: 'PARTNER',
    action: 'CRIAR_VENDA',
    entity: 'Sale',
    entityId: 'sale-003',
    details: 'Venda multi-marca #PB-2026-0184 de R$ 130,00 registrada (Preta Chic + Pikena Biojóias).',
  },
];
